### ISSUE TITLE
How to get access to API?

### ISSUE THREAD

**Issue by qFactorin** [algo2t/alphatrade#5]
What is the process to get access to APIkey and Secret. I tired reaching out to support, but they are not sure weather they can provide access or not and have forwarded the request to developer, which I assume is you.

I have good user base and if API access is provided some 1000 odd users will start using the platform.

**Comment by algo2t** [comment]
This is not official API , just tried to program. There is no need of API and Secret just username password and twofa(same answer for all questions). I already told SAS support team but they are not willing to provide any official api since I guess it comes with cost and more support tickets. It is just an use AS IS - for everyone.

Better use it as it is available and do not disturb SAS team unnecessary. Check Readme properly most of the answer available there.

**Comment by qFactorin** [comment]
Hi, Thank you for your reply. 

Just curious, since there is no support, how reliable or scalable is it to develop application around API. 

Do not think otherwise, asking this as you are a developer, nothing against the product or efforts.

**Comment by algo2t** [comment]
@qFactorin I would suggest not to use for mission critical projects since SAS team says their APIs are not stable. Since SAS is good in some aspects that is the reason I created this unofficial project. You can say it is Use at your own RISK thing.
